# Generated by Django 5.1.2 on 2024-10-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
