# Generated by Django 5.1.2 on 2024-10-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_task_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdiscipline',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='schedule.teacher'),
        ),
    ]
