# Generated by Django 5.1.2 on 2024-10-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_academicdiscipline_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdiscipline',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='schedule.teacher'),
        ),
    ]
