# Generated by Django 5.1.2 on 2025-01-21 17:45

import django.db.models.deletion
import django_ai.schedule.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.CharField(blank=True, max_length=1000)),
                ('link_desk', django_ai.schedule.models.Link(blank=True)),
                ('link_class', django_ai.schedule.models.Link(blank=True)),
                ('link_disk', django_ai.schedule.models.Link(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=django_ai.schedule.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tg_link', django_ai.schedule.models.Link(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('EXAM', 'exam'), ('EXAM_TEST', 'exam_test'), ('LAB', 'lab'), ('TEST', 'test'), ('COURSE_WORK', 'course_work')], default='lab', max_length=11)),
                ('date', models.DateTimeField(blank=True)),
                ('link', django_ai.schedule.models.Link(blank=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('group', models.BooleanField(default=False, help_text='Can be performed by a group.')),
                ('work_space', django_ai.schedule.models.Link(blank=True)),
                ('group_work_space', django_ai.schedule.models.Link(blank=True)),
                ('discipline', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.academicdiscipline')),
            ],
        ),
        migrations.AddField(
            model_name='academicdiscipline',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='schedule.teacher'),
        ),
    ]
