# Generated by Django 5.1.2 on 2025-01-21 23:54

import django_ai.schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_imagemodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=django_ai.schedule.models.upload_to),
        ),
    ]
